SELECT * FROM R_USER_ROLES;
SELECT * FROM R_ROLE_PERMISSIONS;
SELECT * FROM M_USER;
SELECT * FROM M_ROLE;
SELECT * FROM M_PERMISSION;


SELECT
    mr.ROLE_ID
     , mr.ROLE
     , mr.ROLE_NAME
     , mr.DESCRIPTION
     , mr.CREATE_USER
     , mr.CREATED
     , mr.UPDATE_USER
     , mr.UPDATED
     , mr.LOCKED
FROM R_USER_ROLES rur LEFT JOIN M_ROLE mr ON rur.ROLE_ID=mr.ROLE_ID WHERE rur.USER_ID=1