SELECT * FROM R_USER_ROLE;
SELECT * FROM R_ROLE_PERMISSION;
SELECT * FROM M_USER;
SELECT * FROM M_ROLE;
SELECT * FROM M_PERMISSION;


INSERT INTO M_USER (USER_ID, USERNAME, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, BIRTHDAY, LAST_LOGIN, CREATE_USER, CREATED, UPDATE_USER, UPDATED, ACTIVE_KBN) VALUES (1, 'tangzh1983', 'tangzh1983@gmail.com', '123456', '湯', '志華', TO_TIMESTAMP('1983-11-20 21:02:18.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), TO_TIMESTAMP('2019-12-29 21:02:36.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), 'tangzh1983', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO M_ROLE (ROLE_ID, ROLE_NAME, DISPLAY_NAME, DESCRIPTION, CREATE_USER, CREATED, UPDATE_USER, UPDATED, ACTIVE_KBN) VALUES (1, 'admin', '管理者', '管理者', 'tangzh1983', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO R_USER_ROLE (USER_ID, ROLE_ID, CREATE_USER, CREATED, UPDATE_USER, UPDATED, ACTIVE_KBN) VALUES (1, 1, 'tangzh1983', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO M_PERMISSION (PERMISSION_ID, PERMISSION_NAME, DESCRIPTION, URL, CREATE_USER, CREATED, UPDATE_USER, UPDATED, ACTIVE_KBN) VALUES (1, 'ログイン', '統一ログイン画面', '/admin/login', 'tangzh1983', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO R_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID, CREATE_USER, CREATED, UPDATE_USER, UPDATED, ACTIVE_KBN) VALUES (1, 1, 'tangzh1983', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

select
    USER_ID
     , USERNAME
     , EMAIL
     , PASSWORD
     , FIRST_NAME
     , LAST_NAME
     , BIRTHDAY
     , LAST_LOGIN
     , CREATE_USER
     , CREATED
     , UPDATE_USER
     , UPDATED
     , ACTIVE_KBN
    from M_USER
    where USERNAME = 'tangzh1983';

SELECT mr.ROLE_ID, mr.ROLE_NAME, mr.DISPLAY_NAME, mr.DESCRIPTION, mr.CREATE_USER, mr.CREATED, mr.UPDATE_USER, mr.UPDATED, mr.ACTIVE_KBN FROM M_ROLE mr LEFT JOIN R_USER_ROLE rur ON mr.ROLE_ID = rur.ROLE_ID LEFT JOIN M_USER mu ON rur.USER_ID=mu.USER_ID WHERE mu.USERNAME='tangzh1983' AND mr.ACTIVE_KBN=1 AND rur.ACTIVE_KBN=1 AND mu.ACTIVE_KBN=1;


SELECT USER_ID, USERNAME, PASSWORD, ACTIVE_KBN FROM M_USER WHERE USERNAME= 'tangzh1983' AND ACTIVE_KBN=1;